
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["615 620 1", "620 625 2", "625 630 3", "630 635 4", "635 640 5", "640 645 6", "645 650 7", "650 655 8", "655 660 9", "660 665 10", "665 670 11", "670 675 12", "675 680 13", "680 685 14", "685 690 15", "690 695 16", "695 700 17", "700 705 18", "705 710 19", "710 715 20", "715 720 21", "720 725 22", "725 730 23", "730 735 24", "735 740 25", "740 745 26", "745 750 27", "750 755 28", "755 760 29", "760 765 30", "765 770 31", "770 775 32", "775 780 33", "780 785 34", "785 790 35", "790 795 36", "795 800 37", "800 805 38", "805 810 39", "810 815 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
