
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["9400 9405 1", "9405 9410 2", "9410 9415 3", "9415 9420 4", "9420 9425 5", "9425 9430 6", "9430 9435 7", "9435 9440 8", "9440 9445 9", "9445 9450 10", "9450 9455 11", "9455 9460 12", "9460 9465 13", "9465 9470 14", "9470 9475 15", "9475 9480 16", "9480 9485 17", "9485 9490 18", "9490 9495 19", "9495 9500 20", "9500 9505 21", "9505 9510 22", "9510 9515 23", "9515 9520 24", "9520 9525 25", "9525 9530 26", "9530 9535 27", "9535 9540 28", "9540 9545 29", "9545 9550 30", "9550 9555 31", "9555 9560 32", "9560 9565 33", "9565 9570 34", "9570 9575 35", "9575 9580 36", "9580 9585 37", "9585 9590 38", "9590 9595 39", "9595 9600 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
