
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8415 8420 1", "8420 8425 2", "8425 8430 3", "8430 8435 4", "8435 8440 5", "8440 8445 6", "8445 8450 7", "8450 8455 8", "8455 8460 9", "8460 8465 10", "8465 8470 11", "8470 8475 12", "8475 8480 13", "8480 8485 14", "8485 8490 15", "8490 8495 16", "8495 8500 17", "8500 8505 18", "8505 8510 19", "8510 8515 20", "8515 8520 21", "8520 8525 22", "8525 8530 23", "8530 8535 24", "8535 8540 25", "8540 8545 26", "8545 8550 27", "8550 8555 28", "8555 8560 29", "8560 8565 30", "8565 8570 31", "8570 8575 32", "8575 8580 33", "8580 8585 34", "8585 8590 35", "8590 8595 36", "8595 8600 37", "8600 8605 38", "8605 8610 39", "8610 8615 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
