
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8200 8205 1", "8205 8210 2", "8210 8215 3", "8215 8220 4", "8220 8225 5", "8225 8230 6", "8230 8235 7", "8235 8240 8", "8240 8245 9", "8245 8250 10", "8250 8255 11", "8255 8260 12", "8260 8265 13", "8265 8270 14", "8270 8275 15", "8275 8280 16", "8280 8285 17", "8285 8290 18", "8290 8295 19", "8295 8300 20", "8300 8305 21", "8305 8310 22", "8310 8315 23", "8315 8320 24", "8320 8325 25", "8325 8330 26", "8330 8335 27", "8335 8340 28", "8340 8345 29", "8345 8350 30", "8350 8355 31", "8355 8360 32", "8360 8365 33", "8365 8370 34", "8370 8375 35", "8375 8380 36", "8380 8385 37", "8385 8390 38", "8390 8395 39", "8395 8400 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
