
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8800 8805 1", "8805 8810 2", "8810 8815 3", "8815 8820 4", "8820 8825 5", "8825 8830 6", "8830 8835 7", "8835 8840 8", "8840 8845 9", "8845 8850 10", "8850 8855 11", "8855 8860 12", "8860 8865 13", "8865 8870 14", "8870 8875 15", "8875 8880 16", "8880 8885 17", "8885 8890 18", "8890 8895 19", "8895 8900 20", "8900 8905 21", "8905 8910 22", "8910 8915 23", "8915 8920 24", "8920 8925 25", "8925 8930 26", "8930 8935 27", "8935 8940 28", "8940 8945 29", "8945 8950 30", "8950 8955 31", "8955 8960 32", "8960 8965 33", "8965 8970 34", "8970 8975 35", "8975 8980 36", "8980 8985 37", "8985 8990 38", "8990 8995 39", "8995 9000 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
