
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8400 8405 1", "8405 8410 2", "8410 8415 3", "8415 8420 4", "8420 8425 5", "8425 8430 6", "8430 8435 7", "8435 8440 8", "8440 8445 9", "8445 8450 10", "8450 8455 11", "8455 8460 12", "8460 8465 13", "8465 8470 14", "8470 8475 15", "8475 8480 16", "8480 8485 17", "8485 8490 18", "8490 8495 19", "8495 8500 20", "8500 8505 21", "8505 8510 22", "8510 8515 23", "8515 8520 24", "8520 8525 25", "8525 8530 26", "8530 8535 27", "8535 8540 28", "8540 8545 29", "8545 8550 30", "8550 8555 31", "8555 8560 32", "8560 8565 33", "8565 8570 34", "8570 8575 35", "8575 8580 36", "8580 8585 37", "8585 8590 38", "8590 8595 39", "8595 8600 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
