
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["9000 9005 1", "9005 9010 2", "9010 9015 3", "9015 9020 4", "9020 9025 5", "9025 9030 6", "9030 9035 7", "9035 9040 8", "9040 9045 9", "9045 9050 10", "9050 9055 11", "9055 9060 12", "9060 9065 13", "9065 9070 14", "9070 9075 15", "9075 9080 16", "9080 9085 17", "9085 9090 18", "9090 9095 19", "9095 9100 20", "9100 9105 21", "9105 9110 22", "9110 9115 23", "9115 9120 24", "9120 9125 25", "9125 9130 26", "9130 9135 27", "9135 9140 28", "9140 9145 29", "9145 9150 30", "9150 9155 31", "9155 9160 32", "9160 9165 33", "9165 9170 34", "9170 9175 35", "9175 9180 36", "9180 9185 37", "9185 9190 38", "9190 9195 39", "9195 9200 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
