
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["15 20 1", "15 20 2", "20 25 3", "20 25 4", "25 30 5", "25 30 6", "30 35 7", "30 35 8", "35 40 9", "35 40 10", "40 45 11", "40 45 12", "45 50 13", "45 50 14", "50 55 15", "50 55 16", "55 60 17", "55 60 18", "60 65 19", "60 65 20", "65 70 21", "65 70 22", "70 75 23", "70 75 24", "75 80 25", "75 80 26", "80 85 27", "80 85 28", "85 90 29", "85 90 30", "90 95 31", "90 95 32", "95 100 33", "95 100 34", "100 105 35", "100 105 36", "105 110 37", "105 110 38", "110 115 39", "110 115 40", "115 120 41", "115 120 42", "120 125 43", "120 125 44", "125 130 45", "125 130 46", "130 135 47", "130 135 48", "135 140 49", "135 140 50", "140 145 51", "140 145 52", "145 150 53", "145 150 54", "150 155 55", "150 155 56", "155 160 57", "155 160 58", "160 165 59", "160 165 60", "165 170 61", "165 170 62", "170 175 63", "170 175 64", "175 180 65", "175 180 66", "180 185 67", "180 185 68", "185 190 69", "185 190 70", "190 195 71", "190 195 72", "195 200 73", "195 200 74", "200 205 75", "200 205 76", "205 210 77", "205 210 78", "210 215 79", "210 215 80"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
