
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["0 5 1", "0 5 2", "5 10 3", "5 10 4", "10 15 5", "10 15 6", "15 20 7", "15 20 8", "20 25 9", "20 25 10", "25 30 11", "25 30 12", "30 35 13", "30 35 14", "35 40 15", "35 40 16", "40 45 17", "40 45 18", "45 50 19", "45 50 20", "50 55 21", "50 55 22", "55 60 23", "55 60 24", "60 65 25", "60 65 26", "65 70 27", "65 70 28", "70 75 29", "70 75 30", "75 80 31", "75 80 32", "80 85 33", "80 85 34", "85 90 35", "85 90 36", "90 95 37", "90 95 38", "95 100 39", "95 100 40", "100 105 41", "100 105 42", "105 110 43", "105 110 44", "110 115 45", "110 115 46", "115 120 47", "115 120 48", "120 125 49", "120 125 50", "125 130 51", "125 130 52", "130 135 53", "130 135 54", "135 140 55", "135 140 56", "140 145 57", "140 145 58", "145 150 59", "145 150 60", "150 155 61", "150 155 62", "155 160 63", "155 160 64", "160 165 65", "160 165 66", "165 170 67", "165 170 68", "170 175 69", "170 175 70", "175 180 71", "175 180 72", "180 185 73", "180 185 74", "185 190 75", "185 190 76", "190 195 77", "190 195 78", "195 200 79", "195 200 80"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
