
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8615 8620 1", "8620 8625 2", "8625 8630 3", "8630 8635 4", "8635 8640 5", "8640 8645 6", "8645 8650 7", "8650 8655 8", "8655 8660 9", "8660 8665 10", "8665 8670 11", "8670 8675 12", "8675 8680 13", "8680 8685 14", "8685 8690 15", "8690 8695 16", "8695 8700 17", "8700 8705 18", "8705 8710 19", "8710 8715 20", "8715 8720 21", "8720 8725 22", "8725 8730 23", "8730 8735 24", "8735 8740 25", "8740 8745 26", "8745 8750 27", "8750 8755 28", "8755 8760 29", "8760 8765 30", "8765 8770 31", "8770 8775 32", "8775 8780 33", "8780 8785 34", "8785 8790 35", "8790 8795 36", "8795 8800 37", "8800 8805 38", "8805 8810 39", "8810 8815 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
