
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["415 420 1", "420 425 2", "425 430 3", "430 435 4", "435 440 5", "440 445 6", "445 450 7", "450 455 8", "455 460 9", "460 465 10", "465 470 11", "470 475 12", "475 480 13", "480 485 14", "485 490 15", "490 495 16", "495 500 17", "500 505 18", "505 510 19", "510 515 20", "515 520 21", "520 525 22", "525 530 23", "530 535 24", "535 540 25", "540 545 26", "545 550 27", "550 555 28", "555 560 29", "560 565 30", "565 570 31", "570 575 32", "575 580 33", "580 585 34", "585 590 35", "590 595 36", "595 600 37", "600 605 38", "605 610 39", "610 615 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
