
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["9415 9420 1", "9420 9425 2", "9425 9430 3", "9430 9435 4", "9435 9440 5", "9440 9445 6", "9445 9450 7", "9450 9455 8", "9455 9460 9", "9460 9465 10", "9465 9470 11", "9470 9475 12", "9475 9480 13", "9480 9485 14", "9485 9490 15", "9490 9495 16", "9495 9500 17", "9500 9505 18", "9505 9510 19", "9510 9515 20", "9515 9520 21", "9520 9525 22", "9525 9530 23", "9530 9535 24", "9535 9540 25", "9540 9545 26", "9545 9550 27", "9550 9555 28", "9555 9560 29", "9560 9565 30", "9565 9570 31", "9570 9575 32", "9575 9580 33", "9580 9585 34", "9585 9590 35", "9590 9595 36", "9595 9600 37", "9600 9605 38", "9605 9610 39", "9610 9615 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
