
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8015 8020 1", "8020 8025 2", "8025 8030 3", "8030 8035 4", "8035 8040 5", "8040 8045 6", "8045 8050 7", "8050 8055 8", "8055 8060 9", "8060 8065 10", "8065 8070 11", "8070 8075 12", "8075 8080 13", "8080 8085 14", "8085 8090 15", "8090 8095 16", "8095 8100 17", "8100 8105 18", "8105 8110 19", "8110 8115 20", "8115 8120 21", "8120 8125 22", "8125 8130 23", "8130 8135 24", "8135 8140 25", "8140 8145 26", "8145 8150 27", "8150 8155 28", "8155 8160 29", "8160 8165 30", "8165 8170 31", "8170 8175 32", "8175 8180 33", "8180 8185 34", "8185 8190 35", "8190 8195 36", "8195 8200 37", "8200 8205 38", "8205 8210 39", "8210 8215 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
