
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["0 5 1", "5 10 2", "10 15 3", "15 20 4", "20 25 5", "25 30 6", "30 35 7", "35 40 8", "40 45 9", "45 50 10", "50 55 11", "55 60 12", "60 65 13", "65 70 14", "70 75 15", "75 80 16", "80 85 17", "85 90 18", "90 95 19", "95 100 20", "100 105 21", "105 110 22", "110 115 23", "115 120 24", "120 125 25", "125 130 26", "130 135 27", "135 140 28", "140 145 29", "145 150 30", "150 155 31", "155 160 32", "160 165 33", "165 170 34", "170 175 35", "175 180 36", "180 185 37", "185 190 38", "190 195 39", "195 200 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
