
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["8600 8605 1", "8605 8610 2", "8610 8615 3", "8615 8620 4", "8620 8625 5", "8625 8630 6", "8630 8635 7", "8635 8640 8", "8640 8645 9", "8645 8650 10", "8650 8655 11", "8655 8660 12", "8660 8665 13", "8665 8670 14", "8670 8675 15", "8675 8680 16", "8680 8685 17", "8685 8690 18", "8690 8695 19", "8695 8700 20", "8700 8705 21", "8705 8710 22", "8710 8715 23", "8715 8720 24", "8720 8725 25", "8725 8730 26", "8730 8735 27", "8735 8740 28", "8740 8745 29", "8745 8750 30", "8750 8755 31", "8755 8760 32", "8760 8765 33", "8765 8770 34", "8770 8775 35", "8775 8780 36", "8780 8785 37", "8785 8790 38", "8790 8795 39", "8795 8800 40"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
